-- Tabela de Serviços
CREATE TABLE IF NOT EXISTS servicos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  descricao TEXT,
  preco NUMERIC NOT NULL,
  duracao INTEGER NOT NULL,
  categoria TEXT,
  ativo BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela de Profissionais
CREATE TABLE IF NOT EXISTS profissionais (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  email TEXT,
  telefone TEXT,
  especialidade TEXT,
  foto TEXT,
  ativo BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela de Galeria
CREATE TABLE IF NOT EXISTS galeria (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT NOT NULL,
  imagem TEXT NOT NULL,
  categoria TEXT,
  ativo BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela de Clientes
CREATE TABLE IF NOT EXISTS clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  email TEXT,
  telefone TEXT,
  observacoes TEXT,
  foto TEXT,
  ativo BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela de Agendamentos
CREATE TABLE IF NOT EXISTS agendamentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data TEXT NOT NULL,
  horario TEXT NOT NULL,
  cliente_id BIGINT REFERENCES clientes(id),
  servico_id BIGINT REFERENCES servicos(id),
  profissional_id BIGINT REFERENCES profissionais(id),
  status TEXT DEFAULT 'PENDENTE',
  telefone TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela de Configurações
CREATE TABLE IF NOT EXISTS configuracoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chave TEXT UNIQUE NOT NULL,
  valor TEXT NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Inserir configurações iniciais
INSERT INTO configuracoes (chave, valor) VALUES 
  ('horario_abertura', '08:00'),
  ('horario_fechamento', '20:00'),
  ('dias_funcionamento', 'Seg,Ter,Qua,Qui,Sex,Sáb'),
  ('status_loja', 'ABERTO')
ON CONFLICT (chave) DO NOTHING;

-- Seed de Serviços
INSERT INTO servicos (nome, descricao, preco, duracao, categoria) VALUES
  ('Manicure', 'Cuidados completos para suas mãos', 35, 30, 'Manicure'),
  ('Manicure + Esmaltação', 'Esmalte gel que dura semanas', 45, 45, 'Manicure'),
  ('Pedicure SPA', 'Pés renovada e relaxamento garantido', 65, 60, 'Pedicure'),
  ('Extensão de Cílios', 'Olhar mais bonito sem esforço', 150, 90, 'Cílios'),
  ('Design de Sobrancelha', 'O formato ideal para seu rosto', 30, 20, 'Sobrancelha'),
  ('Massagem Relaxante', 'Uma hora só para você', 80, 60, 'Massagem');

-- Seed de Profissionais
INSERT INTO profissionais (nome, especialidade) VALUES
  ('Carla Silva', 'Manicure'),
  ('Juliana Santos', 'Sobrancelha'),
  ('Marina Oliveira', 'Massagem'),
  ('Patrícia Lima', 'Cílios');

-- Seed de Galeria
INSERT INTO galeria (titulo, imagem, categoria) VALUES
  ('Spa dos Pés', '/images/pes.jpeg', 'Pedicure'),
  ('Manicure Profissional', '/images/fazendo-a-unha.jfif', 'Manicure'),
  ('Design de Unhas', '/images/unha1.jfif', 'Manicure');