-- Tabela de Serviços
CREATE TABLE IF NOT EXISTS servicos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  descricao TEXT,
  preco NUMERIC NOT NULL,
  duracao INTEGER NOT NULL,
  categoria TEXT,
  ativo BOOLEAN DEFAULT true,
  beneficios TEXT[],
  processo TEXT[],
  imagem TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela de Profissionais
CREATE TABLE IF NOT EXISTS profissionais (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  email TEXT,
  telefone TEXT,
  especialidade TEXT,
  foto TEXT,
  ativo BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela de Galeria
CREATE TABLE IF NOT EXISTS galeria (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT NOT NULL,
  imagem TEXT NOT NULL,
  categoria TEXT,
  ativo BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela de Clientes
CREATE TABLE IF NOT EXISTS clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  email TEXT,
  telefone TEXT,
  observacoes TEXT,
  foto TEXT,
  ativo BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela de Agendamentos
CREATE TABLE IF NOT EXISTS agendamentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data TEXT NOT NULL,
  horario TEXT NOT NULL,
  servico_id BIGINT REFERENCES servicos(id),
  profissional_id BIGINT REFERENCES profissionais(id),
  status TEXT DEFAULT 'PENDENTE',
  telefone TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabela de Configurações
CREATE TABLE IF NOT EXISTS configuracoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chave TEXT UNIQUE NOT NULL,
  valor TEXT NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS
ALTER TABLE servicos ENABLE ROW LEVEL SECURITY;
ALTER TABLE profissionais ENABLE ROW LEVEL SECURITY;
ALTER TABLE galeria ENABLE ROW LEVEL SECURITY;
ALTER TABLE clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE agendamentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE configuracoes ENABLE ROW LEVEL SECURITY;

-- Políticas públicas para leitura
CREATE POLICY "Public read servicos" ON servicos FOR SELECT USING (true);
CREATE POLICY "Public read profissionais" ON profissionais FOR SELECT USING (true);
CREATE POLICY "Public read galeria" ON galeria FOR SELECT USING (true);
CREATE POLICY "Public read clientes" ON clientes FOR SELECT USING (true);
CREATE POLICY "Public read agendamentos" ON agendamentos FOR SELECT USING (true);
CREATE POLICY "Public read configuracoes" ON configuracoes FOR SELECT USING (true);

-- Políticas para insert (anonimas podem criar agendamentos)
CREATE POLICY "Public insert agendamentos" ON agendamentos FOR INSERT WITH CHECK (true);

-- Políticas para update/delete (apenas autenticado)
CREATE POLICY "Auth update servicos" ON servicos FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Auth delete servicos" ON servicos FOR DELETE USING (auth.role() = 'authenticated');
CREATE POLICY "Auth update profissionais" ON profissionais FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Auth delete profissionais" ON profissionais FOR DELETE USING (auth.role() = 'authenticated');
CREATE POLICY "Auth update galeria" ON galeria FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Auth delete galeria" ON galeria FOR DELETE USING (auth.role() = 'authenticated');

-- Inserir configurações iniciais
INSERT INTO configuracoes (chave, valor) VALUES 
  ('horario_abertura', '08:00'),
  ('horario_fechamento', '20:00'),
  ('dias_funcionamento', 'Seg,Ter,Qua,Qui,Sex,Sáb'),
  ('status_loja', 'ABERTO')
ON CONFLICT (chave) DO NOTHING;

-- Seed de Serviços (apenas se vazio)
INSERT INTO servicos (nome, descricao, preco, duracao, categoria, beneficios, processo, imagem) 
SELECT 'Manicure', 'Cuidados completos para suas mãos', 35, 30, 'Manicure', 
  ARRAY['Limpeza das unhas', 'Cutícula tratada', 'Esmalte simples', 'Hidratação das mãos'],
  ARRAY['Higienização', 'Cutícula', 'Modelagem', 'Esmalte', 'Hidratação'],
  '/gisellestudio/images/fazendo-a-unha.jfif'
WHERE NOT EXISTS (SELECT 1 FROM servicos);

INSERT INTO servicos (nome, descricao, preco, duracao, categoria, beneficios, processo, imagem) 
SELECT 'Manicure + Esmaltação', 'Esmalte gel que dura semanas', 45, 45, 'Manicure',
  ARRAY['Tudo da manicure simples', 'Esmalte gel', 'Maior durabilidade', 'Brilho intenso'],
  ARRAY['Higienização', 'Cutícula', 'Modelagem', 'Esmalte Profissional', 'Secagem UV', 'Hidratação'],
  '/gisellestudio/images/unha1.jfif'
WHERE NOT EXISTS (SELECT 1 FROM servicos WHERE nome = 'Manicure + Esmaltação');

INSERT INTO servicos (nome, descricao, preco, duracao, categoria, beneficios, processo, imagem) 
SELECT 'Pedicure SPA', 'Pés renovada e relaxamento garantido', 65, 60, 'Pedicure',
  ARRAY['Esfoliação profunda', 'Hidratação intensiva', 'Massagem relaxante', 'Esmalte premium'],
  ARRAY['Banho de pés', 'Esfoliação', 'Remoção de calos', 'Hidratação', 'Massagem', 'Esmalte'],
  '/gisellestudio/images/pes.jpeg'
WHERE NOT EXISTS (SELECT 1 FROM servicos WHERE nome = 'Pedicure SPA');

INSERT INTO servicos (nome, descricao, preco, duracao, categoria, beneficios, processo, imagem) 
SELECT 'Extensão de Cílios', 'Olhar mais bonito sem esforço', 150, 90, 'Cílios',
  ARRAY['Volume natural', 'Cílios mais longos', 'Sem necessidade de rímel', 'Duração de 30 dias'],
  ARRAY['Consulta inicial', 'Preparação dos cílios', 'Aplicação fio a fio', 'Secagem', 'Recomendações'],
  'https://images.unsplash.com/photo-1512496015851-a1fbaf6998c2?q=80&w=600&auto=format&fit=crop'
WHERE NOT EXISTS (SELECT 1 FROM servicos WHERE nome = 'Extensão de Cílios');

INSERT INTO servicos (nome, descricao, preco, duracao, categoria, beneficios, processo, imagem) 
SELECT 'Design de Sobrancelha', 'O formato ideal para seu rosto', 30, 20, 'Sobrancelha',
  ARRAY['Formato ideal para seu rosto', 'Simetria perfeita', 'Produto henna natural', 'Duração de 15 dias'],
  ARRAY['Avaliação do rosto', 'Desenho inicial', 'Ajuste conforme preferência', 'Aplicação de henna', 'Finalização'],
  'https://images.unsplash.com/photo-1599305090598-fe179d501227?q=80&w=600&auto=format&fit=crop'
WHERE NOT EXISTS (SELECT 1 FROM servicos WHERE nome = 'Design de Sobrancelha');

INSERT INTO servicos (nome, descricao, preco, duracao, categoria, beneficios, processo, imagem) 
SELECT 'Massagem Relaxante', 'Uma hora só para você', 80, 60, 'Massagem',
  ARRAY['Alívio do estresse', 'Melhora da circulação', 'Relaxamento muscular', 'Sensação de bem-estar'],
  ARRAY['Aromaterapia', 'Massagem corporal', 'Foco em áreas tensionadas', 'Hidratação corporal'],
  'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?q=80&w=600&auto=format&fit=crop'
WHERE NOT EXISTS (SELECT 1 FROM servicos WHERE nome = 'Massagem Relaxante');

-- Seed de Profissionais
INSERT INTO profissionais (nome, especialidade) 
SELECT 'Carla Silva', 'Manicure'
WHERE NOT EXISTS (SELECT 1 FROM profissionais);

INSERT INTO profissionais (nome, especialidade) 
SELECT 'Juliana Santos', 'Sobrancelha'
WHERE NOT EXISTS (SELECT 1 FROM profissionais WHERE nome = 'Juliana Santos');

INSERT INTO profissionais (nome, especialidade) 
SELECT 'Marina Oliveira', 'Massagem'
WHERE NOT EXISTS (SELECT 1 FROM profissionais WHERE nome = 'Marina Oliveira');

INSERT INTO profissionais (nome, especialidade) 
SELECT 'Patrícia Lima', 'Cílios'
WHERE NOT EXISTS (SELECT 1 FROM profissionais WHERE nome = 'Patrícia Lima');

-- Seed de Galeria
INSERT INTO galeria (titulo, imagem, categoria) 
SELECT 'Spa dos Pés', '/gisellestudio/images/pes.jpeg', 'Pedicure'
WHERE NOT EXISTS (SELECT 1 FROM galeria);

INSERT INTO galeria (titulo, imagem, categoria) 
SELECT 'Manicure Profissional', '/gisellestudio/images/fazendo-a-unha.jfif', 'Manicure'
WHERE NOT EXISTS (SELECT 1 FROM galeria WHERE titulo = 'Manicure Profissional');

INSERT INTO galeria (titulo, imagem, categoria) 
SELECT 'Design de Unhas', '/gisellestudio/images/unha1.jfif', 'Manicure'
WHERE NOT EXISTS (SELECT 1 FROM galeria WHERE titulo = 'Design de Unhas');